
package intf;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import cords.DBconnect;
import net.proteanit.sql.DbUtils;

public class data extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    public data() {
        
        initComponents();
        conn=DBconnect.connect();
        tableload();
    }
    
    
    public void tableload(){
    
        try {
            String a="SELECT sno AS NO,sdate AS Date,sdip AS Discription,sva AS Value FROM revenuetable";
            pst=conn.prepareStatement(a);
            rs=pst.executeQuery();
            revtable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         try {
            String a="SELECT id AS NO,date AS Date,dis AS Discription,val AS Value FROM extable";
            pst=conn.prepareStatement(a);
            rs=pst.executeQuery();
            extable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    public void clear(){
    
       cmb.setSelectedIndex(0);
       num.setText("");
       datetxt.setText("");
       distxt.setText("");
       valtxt.setText("");
       searchrev.setText("");
       searchex.setText("");
       sumrevlbl.setText("");
       exsumlbl.setText("");
       profitlbl.setText("");
      tableload();
       
    }
    
    public void tabledata1(){
    
    int r=revtable.getSelectedRow();
    
    String no=revtable.getValueAt(r,0).toString();
    String date=revtable.getValueAt(r,1).toString();
    String dis=revtable.getValueAt(r,2).toString();
    String val=revtable.getValueAt(r,3).toString();
    
    num.setText(no);
    datetxt.setText(date);
    distxt.setText(dis);
    valtxt.setText(val);
    }
    
    public void tabledata2(){
        
    int s=extable.getSelectedRow();
    
    String no1=extable.getValueAt(s,0).toString();
    String date1=extable.getValueAt(s,1).toString();
    String dis1=extable.getValueAt(s,2).toString();
    String val1=extable.getValueAt(s,3).toString();
    
   
    num.setText(no1);
    datetxt.setText(date1);
    distxt.setText(dis1);
    valtxt.setText(val1);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmb = new javax.swing.JComboBox();
        datetxt = new javax.swing.JTextField();
        distxt = new javax.swing.JTextField();
        valtxt = new javax.swing.JTextField();
        exitbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        withbtn = new javax.swing.JButton();
        insertbtn = new javax.swing.JButton();
        labourbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        revlbl = new javax.swing.JLabel();
        prolbl = new javax.swing.JLabel();
        exlbl = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        num = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        extable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        revtable = new javax.swing.JTable();
        searchex = new javax.swing.JTextField();
        searchrev = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profitlbl = new javax.swing.JLabel();
        exdelete = new javax.swing.JButton();
        revdelete = new javax.swing.JButton();
        exsumlbl = new javax.swing.JLabel();
        sumrevlbl = new javax.swing.JLabel();
        profitbtn = new javax.swing.JButton();
        sumrev = new javax.swing.JButton();
        sumex = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("  Date");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("  Reve. or Exp.");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("  Value");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("  No");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("  Discription");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        cmb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Revenue", "Expense" }));
        cmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, 30));

        datetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 30));

        distxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(distxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, 30));

        valtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(valtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, 30));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 80, 30));

        clearbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 80, 30));

        withbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        withbtn.setText("Details of Withdraw");
        withbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        withbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withbtnActionPerformed(evt);
            }
        });
        jPanel2.add(withbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 160, 30));

        insertbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel2.add(insertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, 30));

        labourbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labourbtn.setText("Details of Labour");
        labourbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        labourbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labourbtnActionPerformed(evt);
            }
        });
        jPanel2.add(labourbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 160, 30));

        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel2.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("    Revenue");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("    Expense");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("    Profit");

        revlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        prolbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        exlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, -1));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 30));

        num.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/nm.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 640));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 640);

        extable.setBackground(new java.awt.Color(204, 204, 204));
        extable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        extable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Date", "Discription", "Value"
            }
        ));
        extable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extableMouseClicked(evt);
            }
        });
        extable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(extable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(790, 60, 430, 490);

        revtable.setBackground(new java.awt.Color(204, 204, 204));
        revtable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        revtable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        revtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Date", "Discription", "Value"
            }
        ));
        revtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revtableMouseClicked(evt);
            }
        });
        revtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                revtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(revtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 60, 420, 490);

        searchex.setBackground(new java.awt.Color(204, 204, 204));
        searchex.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchex.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        searchex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchexKeyReleased(evt);
            }
        });
        jPanel1.add(searchex);
        searchex.setBounds(1000, 0, 210, 60);

        searchrev.setBackground(new java.awt.Color(204, 204, 204));
        searchrev.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchrev.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        searchrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchrevActionPerformed(evt);
            }
        });
        searchrev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchrevKeyReleased(evt);
            }
        });
        jPanel1.add(searchrev);
        searchrev.setBounds(560, 0, 210, 60);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("  Revenue");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 10, 70, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("    Expense");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(810, 10, 80, 50);

        profitlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        profitlbl.setForeground(new java.awt.Color(255, 255, 255));
        profitlbl.setText("       ");
        profitlbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.add(profitlbl);
        profitlbl.setBounds(1090, 590, 120, 40);

        exdelete.setText("Delete Table");
        exdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(exdelete);
        exdelete.setBounds(1120, 550, 93, 30);

        revdelete.setText("Delete Table");
        revdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(revdelete);
        revdelete.setBounds(680, 550, 93, 40);

        exsumlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exsumlbl.setForeground(new java.awt.Color(255, 255, 255));
        exsumlbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.add(exsumlbl);
        exsumlbl.setBounds(870, 550, 90, 40);

        sumrevlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sumrevlbl.setForeground(new java.awt.Color(255, 255, 255));
        sumrevlbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.add(sumrevlbl);
        sumrevlbl.setBounds(430, 550, 90, 40);

        profitbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        profitbtn.setText("Profit");
        profitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(profitbtn);
        profitbtn.setBounds(1010, 590, 80, 40);

        sumrev.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sumrev.setText("Sum");
        sumrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumrevActionPerformed(evt);
            }
        });
        jPanel1.add(sumrev);
        sumrev.setBounds(350, 550, 80, 40);

        sumex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sumex.setText("Sum");
        sumex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumexActionPerformed(evt);
            }
        });
        jPanel1.add(sumex);
        sumex.setBounds(790, 550, 80, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/er11.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 0, 450, 640);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/er11.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(770, 0, 450, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1235, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withbtnActionPerformed
        withdraw wd=new withdraw();
        wd.setVisible(true);
    }//GEN-LAST:event_withbtnActionPerformed

    private void labourbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labourbtnActionPerformed
        
        labour lb=new labour();
        lb.setVisible(true);
    }//GEN-LAST:event_labourbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       
        int chk=JOptionPane.showConfirmDialog(null,"Do you want to delete??");
        
       if(chk==0){
    
           int no=Integer.parseInt(num.getText());
           String cmbo=cmb.getSelectedItem().toString();
          
           if(cmbo=="Revenue"){
              
                try{
               String a="DELETE FROM revenuetable WHERE sno='"+no+"' ";
               pst=conn.prepareStatement(a);
               pst.execute();
               tableload();clear();
           
                }catch(Exception e){
                   
                  JOptionPane.showMessageDialog(null,e);
                   }
           
           }
           else{
               try{
               String a="DELETE FROM extable WHERE id='"+no+"' ";
               pst=conn.prepareStatement(a);
               pst.execute();
               tableload();clear();
           
                }catch(Exception e){
                   
                  JOptionPane.showMessageDialog(null,"Can not delete.Try again");
                   }
            }
        }
         
    }//GEN-LAST:event_deletebtnActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
     
        String sel=cmb.getSelectedItem().toString();
        String date=datetxt.getText();
        String dis=distxt.getText();
        int val=Integer.parseInt(valtxt.getText());
        
     if(sel=="Revenue"){
    
           try {
            
            String sql="INSERT INTO revenuetable(sdate,sdip,sva) VALUES ('"+date+"','"+dis+"','"+val+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
     }
     
      if(sel=="Expense"){
    
           try {
            
            String sql="INSERT INTO extable(date,dis,val) VALUES ('"+date+"','"+dis+"','"+val+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
     }
        
        
        tableload();
        clear();
        
        
        
        
        
        
        
    }//GEN-LAST:event_insertbtnActionPerformed

    private void revtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revtableMouseClicked
      
        cmb.setSelectedItem("Revenue");
        tabledata1();
        
    }//GEN-LAST:event_revtableMouseClicked

    private void extableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extableMouseClicked
        cmb.setSelectedItem("Expense");
        tabledata2();
    }//GEN-LAST:event_extableMouseClicked

    private void revtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_revtableKeyReleased
          cmb.setSelectedItem("Revenue");
        tabledata1();  // TODO add your handling code here:
    }//GEN-LAST:event_revtableKeyReleased

    private void extableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extableKeyReleased
           cmb.setSelectedItem("Expense");
        tabledata2();        // TODO add your handling code here:
    }//GEN-LAST:event_extableKeyReleased

    private void searchrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchrevActionPerformed
          
        // TODO add your handling code here:
    }//GEN-LAST:event_searchrevActionPerformed

    private void searchrevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchrevKeyReleased
        
        String srch=searchrev.getText();
        
        try {
            String sql="SELECT * FROM revenuetable WHERE sdate LIKE '%"+srch+"%' OR sdip LIKE '"+srch+"%' OR sva LIKE '"+srch+"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            revtable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchrevKeyReleased

    private void searchexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchexKeyReleased
        
         
        String srch1=searchex.getText();
        
        try {
            String sql="SELECT * FROM extable WHERE date LIKE '%"+srch1+"%' OR dis LIKE '"+srch1+"%' OR val LIKE '"+srch1+"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            extable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_searchexKeyReleased

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        
        String cmbo=cmb.getSelectedItem().toString();
        int no=Integer.parseInt(num.getText());
        String dte=datetxt.getText();
        String dis=distxt.getText();
        String valu=valtxt.getText();
        
        if(cmbo=="Revenue"){
       
            try{
            String sq="UPDATE revenuetable SET sdate='"+dte+"',sdip='"+dis+"',sva='"+valu+"' WHERE sno='"+no+"'";
            pst=conn.prepareStatement(sq);
            pst.execute();
             tableload();
             clear();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Can not updated");
            }
        
        }
        
        if(cmbo=="Expense"){
       
            try{
            String sq="UPDATE extable SET date='"+dte+"',dis='"+dis+"',val='"+valu+"' WHERE id='"+no+"'";
            pst=conn.prepareStatement(sq);
            pst.execute();
             tableload();
             clear();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Can not updated");
            }
           
        
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
      clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    public void sumrev(){
    
       clear();
        int r=revtable.getRowCount();
        int sum=0;
        
        for(int i=0;i<r;i++){
            
           int val=Integer.parseInt(revtable.getValueAt(i, 3).toString());
           sum+=val;
        }
        String a=Integer.toString(sum);
         sumrevlbl.setText(a);
         revlbl.setText(a);
    
    }
    
     public void sumex(){
    
         clear();
        int r1=extable.getRowCount();
        int sum1=0;
        
        for(int i=0;i<r1;i++){
            
           int val=Integer.parseInt(extable.getValueAt(i, 3).toString());
           sum1+=val;
        }
        String a=Integer.toString(sum1);
         exsumlbl.setText(a);
         exlbl.setText(a);
    
    }
     
     public void profit(){
     
     try{    
         clear();
        String rev=revlbl.getText();
        String ex=exlbl.getText();
        
        int rev1=Integer.parseInt(rev);
        int ex1=Integer.parseInt(ex);
        
        int pro=rev1-ex1;
        String t=Integer.toString(pro);
        
        profitlbl.setText(t);
        prolbl.setText(t);
     
     }catch(Exception e){
           JOptionPane.showMessageDialog(null,"First click SUM buttons.");
     }
     }
    
    private void revdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revdeleteActionPerformed
       
        int ch=JOptionPane.showConfirmDialog(null, "Do you want to delete?");
        
        if(ch==0){
        try {
            String a="DELETE FROM revenuetable";
            pst=conn.prepareStatement(a);
            pst.execute();
            tableload();
            clear();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Can not Delete.Try again");
        }
        }
        
    }//GEN-LAST:event_revdeleteActionPerformed

    private void exdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exdeleteActionPerformed
      
         int ch=JOptionPane.showConfirmDialog(null, "Do you want to delete?");
        
        if(ch==0){
        try {
            String a="DELETE FROM extable";
            pst=conn.prepareStatement(a);
            pst.execute();
            tableload();
            clear();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Can not Delete.Try again");
        }
        }
        
    }//GEN-LAST:event_exdeleteActionPerformed

    private void sumrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumrevActionPerformed
       
      sumrev();
     
    }//GEN-LAST:event_sumrevActionPerformed

    private void sumexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumexActionPerformed
        
        sumex();
    }//GEN-LAST:event_sumexActionPerformed

    private void profitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitbtnActionPerformed
          profit();        // TODO add your handling code here:
    }//GEN-LAST:event_profitbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
     System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox cmb;
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField distxt;
    private javax.swing.JButton exdelete;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel exlbl;
    private javax.swing.JLabel exsumlbl;
    private javax.swing.JTable extable;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton labourbtn;
    private javax.swing.JLabel num;
    private javax.swing.JButton profitbtn;
    private javax.swing.JLabel profitlbl;
    private javax.swing.JLabel prolbl;
    private javax.swing.JButton revdelete;
    private javax.swing.JLabel revlbl;
    private javax.swing.JTable revtable;
    private javax.swing.JTextField searchex;
    private javax.swing.JTextField searchrev;
    private javax.swing.JButton sumex;
    private javax.swing.JButton sumrev;
    private javax.swing.JLabel sumrevlbl;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField valtxt;
    private javax.swing.JButton withbtn;
    // End of variables declaration//GEN-END:variables
}
